# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/observability',
                'doc_host': 'https://aiforhealth-xyz.github.io',
                'git_url': 'https://github.com/aiforhealth-xyz/observability',
                'lib_path': 'observability'},
  'syms': {'observability.core': {'observability.core.foo': ('core.html#foo', 'observability/core.py')}, 'observability.medrxiv': {}}}
